#!/usr/bin/env bash
#
# setup-stacks.sh -- Generate CLAUDE.md from policy files
#
# Usage:
#   bash scripts/setup-stacks.sh golang
#   bash scripts/setup-stacks.sh --list
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOCS_DIR="$PROJECT_ROOT/docs"
OUTPUT_FILE="$PROJECT_ROOT/CLAUDE.md"

GENERIC_POLICIES="$DOCS_DIR/policies/GENERIC_POLICIES.md"
POLICIES_DIR="$DOCS_DIR/policies"
STACKS_DIR="$DOCS_DIR/stacks"
INDEX_FILE="$DOCS_DIR/INDEX.md"

# List available stacks
list_stacks() {
    echo "Available stacks:"
    for dir in "$STACKS_DIR"/*/; do
        if [ -d "$dir" ]; then
            stack_name="$(basename "$dir")"
            echo "  $stack_name"
        fi
    done
    echo ""
    echo "Available stack policies:"
    for f in "$POLICIES_DIR"/*_POLICIES.md; do
        if [ -f "$f" ] && [ "$(basename "$f")" != "GENERIC_POLICIES.md" ]; then
            name="$(basename "$f" _POLICIES.md)"
            echo "  $(echo "$name" | tr '[:upper:]' '[:lower:]')"
        fi
    done
}

# Show usage
usage() {
    echo "Usage: $0 [--list] <stack1> [stack2] ..."
    echo ""
    echo "Generates CLAUDE.md by concatenating:"
    echo "  1. docs/policies/GENERIC_POLICIES.md"
    echo "  2. docs/policies/<STACK>_POLICIES.md for each stack"
    echo "  3. docs/INDEX.md"
    echo ""
    echo "Options:"
    echo "  --list    Show available stacks"
    echo ""
    echo "Example:"
    echo "  $0 golang"
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

if [ "$1" = "--list" ]; then
    list_stacks
    exit 0
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    usage
    exit 0
fi

# Verify generic policies exist
if [ ! -f "$GENERIC_POLICIES" ]; then
    echo "Error: Generic policies not found at $GENERIC_POLICIES"
    exit 1
fi

# Start building CLAUDE.md
{
    echo "<!-- AUTO-GENERATED by scripts/setup-stacks.sh -- DO NOT EDIT MANUALLY -->"
    echo "<!-- Stacks: $* -->"
    echo "<!-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ) -->"
    echo ""
    cat "$GENERIC_POLICIES"
    echo ""

    # Add stack-specific policies
    for stack in "$@"; do
        upper_stack="$(echo "$stack" | tr '[:lower:]' '[:upper:]')"
        policy_file="$POLICIES_DIR/${upper_stack}_POLICIES.md"
        if [ -f "$policy_file" ]; then
            echo ""
            echo "---"
            echo ""
            cat "$policy_file"
            echo ""
        else
            echo "Warning: No policy file found for stack '$stack' (looked for $policy_file)" >&2
        fi
    done

    # Add index
    echo ""
    echo "---"
    echo ""
    cat "$INDEX_FILE"

} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE with stacks: $*"
